In [2]:
import os
import gc
import sys
import json
import gzip
import glob
import itertools
import numpy as np
import pandas as pd
import sklearn.manifold
import matplotlib as mpl
import matplotlib.pyplot as plt

from math import comb
from tqdm import tqdm
from copy import deepcopy
from argparse import Namespace
from collections import OrderedDict
from functools import partial
from scipy.stats import multinomial

from ticodm.utils import *
from ticodm.spatial_interaction_model import ProductionConstrained
from ticodm.contingency_table_mcmc import ContingencyTableMarkovChainMonteCarlo
from ticodm.contingency_table import instantiate_ct, ContingencyTable2D

mpl.rcParams['agg.path.chunksize'] = 10000

In [3]:
%matplotlib inline

# AUTO RELOAD EXTERNAL MODULES
%load_ext autoreload
%autoreload 2

This notebook outlines key functionality of the ```ContingencyTable``` and ```ContingencyTableMarkovChainMonteCarlo``` classes that are used for constructing and sampling discrete origin-destination matrices (ODMs), respectively.

# Create a 2D table
Choose a specific number of rows $I$ and number of columns $J$ to create a table.
Rows usually correspond to number of origin locations while columns map to destination locations.

In [4]:
# Fix random seed
np.random.seed(1234)
# Choose 2D table size
I,J = 5,6
# Randomly create a 2D discrete origin-destination matrix
table = np.random.randint(1,50,size=(I*J)).reshape((I,J)).astype('int32')

Initialise a contingency table (another name for discrete origin - destination matrix). Two types of constraints are provided: axes and cells.  The specified below constraint implies that:
1. All rowsums (sums over axis 1) are fixed. This can be the origin demand for a location choice problem.
2. The values of cells (0,1) and (4,2) are fixed. These are specifc OD-pairs.

In [5]:
# Initialise contingency table (discrete origin - destination matrix)
ct = ContingencyTable2D(
    table=table,
    constraints={
        "axes":[[1]],
        "cells":[(0,1),(4,2)]
    }
)

The above initialisation is equivalent to fixed the grand total of the table as follows

In [6]:
# Initialise contingency table (discrete origin - destination matrix)
ct = ContingencyTable2D(
    table=table,
    constraints={
        "axes":[[1],[0,1]],
        "cells":[(0,1),(4,2)]
    }
)

Note that simply writing ```"axes":[1]``` is going to throw an error.

In [7]:
# Initialise contingency table (discrete origin - destination matrix)
ct = ContingencyTable2D(
    table=table,
    constraints={
        "axes":[1],
        "cells":[(0,1),(4,2)]
    }
)

TypeError: object of type 'int' has no len()

We have now initialised a 5x6 ODM.

In [8]:
# View object
ct

5x6 ContingencyTable2(Config)

In [9]:
# Print table
ct.table

array([[48, 20, 39, 13, 25, 16],
       [24, 42, 27, 31, 44, 31],
       [45, 27, 49, 29,  6, 17],
       [10, 48, 49, 13, 38, 35],
       [39,  4, 40, 12,  1, 42]], dtype=int32)

In [10]:
# Print table dimensions
ct.dims

array([5, 6], dtype=uint8)

In [11]:
# Print margins
ct.residual_margins
# ct.margins

{(0,): array([166, 121, 164,  98, 114, 141], dtype=int32),
 (1,): array([141, 199, 173, 193,  98], dtype=int32),
 (0, 1): array([804], dtype=int32)}

Note that fixing the rowsums implies also fixing the grand total of the table indexed by a sum over both 0 and 1 axes.

In [12]:
# Print constrained axes
ct.constraints['constrained_axes']

[(0, 1), (1,)]

In [13]:
# Print margins for constrained axes
for ax in ct.constraints['constrained_axes']:
    print(ax,":",ct.residual_margins[ax],ct.residual_margins[ax].sum())

(0, 1) : [804] 804
(1,) : [141 199 173 193  98] 804


In [14]:
# Print constrained cells
ct.constraints['cells']

[(0, 1), (4, 2)]

In [15]:
# Print values of constrained cells
for c in ct.constraints['cells']:
    print(c,":",ct.table[c])

(0, 1) : 20
(4, 2) : 40


# Deterministic optimisation algorithms

A simple way of generating a table satisfying all constraints is to use iterative residual filling (similar to iterative proportional fitting). This can be done as follows

In [16]:
# Initialise contingency table (discrete origin - destination matrix)
ct = ContingencyTable2D(
    table=table,
    constraints={
        "axes":[[1],[0]],
        "cells":[(0,1),(4,2)]
    }
)

In [17]:
# Obtain solution using mininum residual filling solver
table_solution = ct.table_iterative_residual_filling_solution()

In [18]:
table_solution

array([[ 43,  20,   0,  98,   0,   0],
       [ 25,  60,   0,   0, 114,   0],
       [  0,  61, 112,   0,   0,   0],
       [  0,   0,  52,   0,   0, 141],
       [ 98,   0,  40,   0,   0,   0]], dtype=int32)

In [19]:
# Ensure that table satisfies constraints
ct.table_margins_admissible(table_solution) and ct.table_cells_admissible(table_solution)

True

In [23]:
# Obtain solution using uniform filling solver
table_solution = ct.table_iterative_uniform_residual_filling_solution()

Solution found: False.


{(0,): array([166, 141, 204,  98, 114, 141], dtype=int32), (1,): array([161, 199, 173, 193, 138], dtype=int32), (0, 1): array([864], dtype=int32)}
{(0,): array([166, 121, 164,  98, 114, 141], dtype=int32), (1,): array([141, 199, 173, 193,  98], dtype=int32), (0, 1): array([804], dtype=int32)}


Exception: No solution found

In [21]:
table_solution

array([[ 43,  20,   0,  98,   0,   0],
       [ 25,  60,   0,   0, 114,   0],
       [  0,  61, 112,   0,   0,   0],
       [  0,   0,  52,   0,   0, 141],
       [ 98,   0,  40,   0,   0,   0]], dtype=int32)

In [22]:
# Ensure that table satisfies constraints
ct.table_margins_admissible(table_solution) and ct.table_cells_admissible(table_solution)

True

# Markov Chain Monte Carlo sampling of tables